name: Build & Publish Release APK

on:
  push:
    tags:
      - 'mradityaalok-*'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: setup jdk
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Make Gradle executable
      run: chmod +x ./gradlew

    - name: Build Release APK
      run: |
        export TERMUX_APP_VERSION_NAME="${GITHUB_REF_NAME}" # Used by app/build.gradle
        export TERMUX_APK_VERSION_TAG="${GITHUB_REF_NAME}" # Used by app/build.gradle
        ./gradlew assembleRelease

    - name: Create release
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Creating release with tag '${GITHUB_REF_NAME}'."
        gh release create "${GITHUB_REF_NAME}" ./app/build/outputs/apk/release/*
